[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
mc-connect = { version = "0.1.0", path = ".." }
tokio = { version = "1.45.0", features = ["full"] }
